"""Project opt-in, local state, approvals, and tamper-evident evidence."""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import secrets
import tempfile
import tomllib
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

from pydantic import Field

from preflight.trust import (
    ApprovalGrant,
    CapabilitySet,
    DependencyGraph,
    EvidenceRecord,
    IsolationTier,
    TrustModel,
    canonical_json,
    sha256_bytes,
)

POLICY_NAME = "preflight.toml"
LOCK_NAME = "preflight.lock"
SANDBOX_VERSION = "0.1"
PROJECT_ID_PATTERN = (
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-"
    r"[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)


class ProjectError(ValueError):
    """Project state is absent, invalid, or unsafe to change."""


class ProjectPolicy(TrustModel):
    format: Literal[1] = 1
    project_id: str = Field(pattern=PROJECT_ID_PATTERN)
    active: bool = True
    policy_version: int = Field(default=1, ge=1)
    default_tier: IsolationTier = IsolationTier.STANDARD
    spending: Literal["deny", "exact-approval"] = "deny"
    capabilities: CapabilitySet = Field(default_factory=CapabilitySet)


def local_data_root() -> Path:
    if os.name == "nt":
        base = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData/Local"))
        return base / "Preflight"
    if sys_platform() == "darwin":
        return Path.home() / "Library/Application Support/Preflight"
    return (
        Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local/share"))
        / "preflight"
    )


def sys_platform() -> str:
    import sys

    return sys.platform


def project_state_dir(policy: ProjectPolicy) -> Path:
    return local_data_root() / "projects" / policy.project_id


def find_project(start: Path | str = ".") -> Path | None:
    current = Path(start).resolve()
    if current.is_file():
        current = current.parent
    for candidate in (current, *current.parents):
        if (candidate / POLICY_NAME).is_file():
            return candidate
    return None


def _atomic_write(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(value)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        try:
            Path(temporary).unlink()
        except FileNotFoundError:
            pass


def _reject_link(path: Path, label: str) -> None:
    if path.is_symlink():
        raise ProjectError(f"{label} may not be a symlink: {path}")


def _toml_array(values: tuple[str, ...]) -> str:
    return json.dumps(list(values), ensure_ascii=True)


def write_policy(root: Path, policy: ProjectPolicy) -> None:
    capabilities = policy.capabilities
    lines = [
        "# Generated by Preflight. Commit this policy; it contains no secrets.",
        f"format = {policy.format}",
        f"project_id = {json.dumps(policy.project_id)}",
        f"active = {str(policy.active).lower()}",
        f"policy_version = {policy.policy_version}",
        f"default_tier = {json.dumps(policy.default_tier.value)}",
        f"spending = {json.dumps(policy.spending)}",
        "",
        "[capabilities]",
        f"files = {json.dumps(capabilities.files.value)}",
        f"file_paths = {_toml_array(capabilities.file_paths)}",
        f"network = {json.dumps(capabilities.network.value)}",
        (f"network_destinations = {_toml_array(capabilities.network_destinations)}"),
        f"accounts_actions = {json.dumps(capabilities.accounts_actions.value)}",
        f"account_names = {_toml_array(capabilities.account_names)}",
        f"programs = {json.dumps(capabilities.programs.value)}",
        f"program_names = {_toml_array(capabilities.program_names)}",
        f"devices_ui = {json.dumps(capabilities.devices_ui.value)}",
        f"device_names = {_toml_array(capabilities.device_names)}",
        f"workload = {json.dumps(capabilities.workload.value)}",
        "",
    ]
    _atomic_write(root / POLICY_NAME, "\n".join(lines))


def read_policy(root: Path | str) -> ProjectPolicy:
    path = Path(root).resolve() / POLICY_NAME
    try:
        _reject_link(path, "project policy")
        with path.open("rb") as stream:
            return ProjectPolicy.model_validate(tomllib.load(stream))
    except (OSError, tomllib.TOMLDecodeError, ValueError) as exc:
        raise ProjectError(f"invalid project policy '{path}': {exc}") from exc


def activate_project(root: Path | str) -> ProjectPolicy:
    project = Path(root).resolve()
    if not project.is_dir():
        raise ProjectError(f"project directory does not exist: {project}")
    path = project / POLICY_NAME
    if path.exists():
        policy = read_policy(project)
        if policy.active:
            return policy
        policy = policy.model_copy(
            update={"active": True, "policy_version": policy.policy_version + 1}
        )
    else:
        policy = ProjectPolicy(project_id=str(uuid.uuid4()))
    write_policy(project, policy)
    state = project_state_dir(policy)
    state.mkdir(parents=True, exist_ok=True)
    append_evidence(policy, "project.activated", {"root": str(project)})
    return policy


def deactivate_project(root: Path | str) -> ProjectPolicy:
    project = find_project(root)
    if project is None:
        raise ProjectError("no active or inactive Preflight project found")
    policy = read_policy(project)
    if not policy.active:
        return policy
    updated = policy.model_copy(
        update={"active": False, "policy_version": policy.policy_version + 1}
    )
    write_policy(project, updated)
    append_evidence(updated, "project.deactivated", {"root": str(project)})
    return updated


def write_lock(root: Path, graph: DependencyGraph) -> None:
    payload = {
        "format": 1,
        "graph_sha256": graph.digest,
        "graph": graph.model_dump(mode="json"),
    }
    _atomic_write(
        root / LOCK_NAME,
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
    )


def read_lock(root: Path | str) -> DependencyGraph:
    path = Path(root).resolve() / LOCK_NAME
    try:
        _reject_link(path, "dependency lock")
        payload = json.loads(path.read_text(encoding="utf-8"))
        graph = DependencyGraph.model_validate(payload["graph"])
        if payload["graph_sha256"] != graph.digest:
            raise ProjectError(f"dependency lock digest does not match: {path}")
        return graph
    except (OSError, UnicodeError, json.JSONDecodeError, KeyError, ValueError) as exc:
        if isinstance(exc, ProjectError):
            raise
        raise ProjectError(f"invalid dependency lock '{path}': {exc}") from exc


def _key(policy: ProjectPolicy) -> bytes:
    path = project_state_dir(policy) / "audit.key"
    _reject_link(path, "audit key")
    if path.is_file():
        value = path.read_bytes()
        if len(value) != 32:
            raise ProjectError(f"invalid audit key: {path}")
        return value
    path.parent.mkdir(parents=True, exist_ok=True)
    value = secrets.token_bytes(32)
    handle, temporary = tempfile.mkstemp(prefix=".audit-key.", dir=path.parent)
    try:
        with os.fdopen(handle, "wb") as stream:
            stream.write(value)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, 0o600)
        os.replace(temporary, path)
    finally:
        try:
            Path(temporary).unlink()
        except FileNotFoundError:
            pass
    return value


def read_evidence(policy: ProjectPolicy) -> tuple[EvidenceRecord, ...]:
    path = project_state_dir(policy) / "evidence.jsonl"
    _reject_link(path, "evidence store")
    if not path.is_file():
        return ()
    records: list[EvidenceRecord] = []
    previous: str | None = None
    key = _key(policy)
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        try:
            record = EvidenceRecord.model_validate_json(line)
        except ValueError as exc:
            raise ProjectError(
                f"invalid evidence record at line {number}: {exc}"
            ) from exc
        body = record.model_dump(mode="json", exclude={"record_sha256", "hmac_sha256"})
        digest = sha256_bytes(canonical_json(body))
        signature = hmac.new(key, bytes.fromhex(digest), hashlib.sha256).hexdigest()
        if (
            record.sequence != number
            or record.project_id != policy.project_id
            or record.previous_sha256 != previous
            or record.record_sha256 != digest
            or not hmac.compare_digest(record.hmac_sha256, signature)
        ):
            raise ProjectError(f"evidence chain verification failed at line {number}")
        records.append(record)
        previous = digest
    return tuple(records)


def append_evidence(
    policy: ProjectPolicy, event: str, data: dict[str, Any]
) -> EvidenceRecord:
    records = read_evidence(policy)
    body = {
        "format": 1,
        "sequence": len(records) + 1,
        "event": event,
        "project_id": policy.project_id,
        "recorded_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
        "data": data,
        "previous_sha256": records[-1].record_sha256 if records else None,
    }
    digest = sha256_bytes(canonical_json(body))
    signature = hmac.new(
        _key(policy), bytes.fromhex(digest), hashlib.sha256
    ).hexdigest()
    record = EvidenceRecord.model_validate(
        {**body, "record_sha256": digest, "hmac_sha256": signature}
    )
    path = project_state_dir(policy) / "evidence.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8", newline="\n") as stream:
        stream.write(record.model_dump_json() + "\n")
        stream.flush()
        os.fsync(stream.fileno())
    return record


def _approval_path(policy: ProjectPolicy) -> Path:
    return project_state_dir(policy) / "approvals.json"


def read_approvals(policy: ProjectPolicy) -> tuple[ApprovalGrant, ...]:
    path = _approval_path(policy)
    _reject_link(path, "approval store")
    if not path.is_file():
        return ()
    try:
        values = json.loads(path.read_text(encoding="utf-8"))
        return tuple(ApprovalGrant.model_validate(value) for value in values)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        raise ProjectError(f"invalid approval store '{path}': {exc}") from exc


def grant_approval(
    policy: ProjectPolicy,
    graph: DependencyGraph,
    *,
    tier: IsolationTier,
) -> ApprovalGrant:
    grant = ApprovalGrant(
        approval_id=str(uuid.uuid4()),
        project_id=policy.project_id,
        artifact_sha256=graph.root.content_sha256,
        dependency_graph_sha256=graph.digest,
        entrypoint_sha256=graph.entrypoint_digest,
        capability_sha256=policy.capabilities.digest,
        policy_version=policy.policy_version,
        sandbox_version=SANDBOX_VERSION,
        tier=tier,
    )
    approvals = (*read_approvals(policy), grant)
    _atomic_write(
        _approval_path(policy),
        json.dumps(
            [item.model_dump(mode="json") for item in approvals],
            indent=2,
            sort_keys=True,
        )
        + "\n",
    )
    append_evidence(
        policy,
        "approval.granted",
        {"approval_id": grant.approval_id, "binding": approval_binding(grant)},
    )
    return grant


def approval_binding(grant: ApprovalGrant) -> str:
    return sha256_bytes(
        canonical_json(grant.model_dump(mode="json", exclude={"granted_at"}))
    )


def matching_approval(
    policy: ProjectPolicy,
    graph: DependencyGraph,
    tier: IsolationTier,
) -> ApprovalGrant | None:
    evidence = read_evidence(policy)
    granted = {
        str(record.data.get("approval_id")): str(record.data.get("binding"))
        for record in evidence
        if record.event == "approval.granted"
    }
    revoked = {
        str(record.data.get("approval_id"))
        for record in evidence
        if record.event == "approval.revoked"
    }
    for grant in reversed(read_approvals(policy)):
        if (
            grant.active
            and grant.approval_id not in revoked
            and granted.get(grant.approval_id) == approval_binding(grant)
            and grant.project_id == policy.project_id
            and grant.artifact_sha256 == graph.root.content_sha256
            and grant.dependency_graph_sha256 == graph.digest
            and grant.entrypoint_sha256 == graph.entrypoint_digest
            and grant.capability_sha256 == policy.capabilities.digest
            and grant.policy_version == policy.policy_version
            and grant.sandbox_version == SANDBOX_VERSION
            and grant.tier == tier
        ):
            return grant
    return None


def revoke_approval(policy: ProjectPolicy, approval_id: str) -> ApprovalGrant:
    approvals = list(read_approvals(policy))
    for index, grant in enumerate(approvals):
        if grant.approval_id == approval_id and grant.active:
            revoked = grant.model_copy(update={"revoked_at": datetime.now(UTC)})
            approvals[index] = revoked
            _atomic_write(
                _approval_path(policy),
                json.dumps(
                    [item.model_dump(mode="json") for item in approvals],
                    indent=2,
                    sort_keys=True,
                )
                + "\n",
            )
            append_evidence(policy, "approval.revoked", {"approval_id": approval_id})
            return revoked
    raise ProjectError(f"active approval not found: {approval_id}")
