"""Fail a release when an archive contains local state or unsafe paths."""

from __future__ import annotations

import sys
import tarfile
import zipfile
from pathlib import Path, PurePosixPath

FORBIDDEN_PARTS = {
    ".git",
    ".mypy_cache",
    ".omc",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
}
FORBIDDEN_SUFFIXES = {".pyc", ".pyo"}
MAX_MEMBERS = 10_000


def validate_name(name: str) -> str | None:
    normalized = name.replace(chr(92), "/")
    path = PurePosixPath(normalized)
    if path.is_absolute() or ".." in path.parts:
        return f"unsafe archive path: {name}"
    if FORBIDDEN_PARTS.intersection(path.parts):
        return f"local state in archive: {name}"
    if path.suffix in FORBIDDEN_SUFFIXES:
        return f"generated bytecode in archive: {name}"
    return None


def audit_wheel(path: Path) -> list[str]:
    findings: list[str] = []
    with zipfile.ZipFile(path) as archive:
        names = archive.namelist()
        if len(names) > MAX_MEMBERS:
            findings.append(f"{path.name}: too many members ({len(names)})")
        findings.extend(
            f"{path.name}: {problem}"
            for name in names
            if (problem := validate_name(name)) is not None
        )
        if not any(name.endswith(".dist-info/METADATA") for name in names):
            findings.append(f"{path.name}: missing wheel metadata")
    return findings


def audit_sdist(path: Path) -> list[str]:
    findings: list[str] = []
    with tarfile.open(path, mode="r:gz") as archive:
        members = archive.getmembers()
        if len(members) > MAX_MEMBERS:
            findings.append(f"{path.name}: too many members ({len(members)})")
        for member in members:
            if problem := validate_name(member.name):
                findings.append(f"{path.name}: {problem}")
            if member.issym() or member.islnk():
                findings.append(
                    f"{path.name}: link member is not allowed: {member.name}"
                )
    return findings


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    root = Path(args[0] if args else "dist")
    wheels = sorted(root.glob("*.whl"))
    sdists = sorted(root.glob("*.tar.gz"))
    findings: list[str] = []
    if len(wheels) != 1:
        findings.append(f"expected exactly one wheel, found {len(wheels)}")
    if len(sdists) != 1:
        findings.append(f"expected exactly one sdist, found {len(sdists)}")
    for wheel in wheels:
        findings.extend(audit_wheel(wheel))
    for sdist in sdists:
        findings.extend(audit_sdist(sdist))
    if findings:
        for finding in findings:
            print(f"REFUSED: {finding}", file=sys.stderr)
        return 1
    print(f"audited {wheels[0].name} and {sdists[0].name}: clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
